<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Antivirus de la passerelle';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'La valeur de blocage de l\'archive cryptée n\'est pas valide.';
$lang['antivirus_block_encrypted_files'] = 'Bloquer les fichiers cryptés';
$lang['antivirus_every_two_hours'] = 'Toutes les deux heures';
$lang['antivirus_maximum_file_size'] = 'Taille maxi dans fichiers Zip';
$lang['antivirus_maximum_file_size_invalid'] = 'La taille maximale de fichier est invalide.';
$lang['antivirus_maximum_files'] = 'Maximum de fichiers dans fichiers Zip';
$lang['antivirus_maximum_files_invalid'] = 'Le nombre maximum de fichiers est invalide.';
$lang['antivirus_maximum_recursion'] = 'Récursivité maxi dans fichiers Zip';
$lang['antivirus_maximum_recursion_invalid'] = 'La récursivité maximale est invalide.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'L\'état d\'analyse de dissimulation SSL est invalide.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'L\'état d\'analyse de discordance d\'URL SSL est invalide.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'L\'état d\'analyse d\'URLs est invalide.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'L\'état d\'analyse des signatures d\'hameçonnage est invalide.';
$lang['antivirus_twice_a_day'] = 'Deux fois par jour';
$lang['antivirus_update_interval'] = 'Intervalle d\'actualisation';
$lang['antivirus_updates_per_day_invalid'] = 'Le nombre de mises à jour par jour n\'est pas valide.';
