<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Gateway Antivirüs';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Þifrelenmiþ dosyalarý engellemek için girilen deðer geçersiz.';
$lang['antivirus_block_encrypted_files'] = 'Þifreli Dosyalarý Engelle';
$lang['antivirus_every_two_hours'] = '2 Saatte Bir';
$lang['antivirus_maximum_file_size'] = 'Zip dosyalarýndaki dosyalar için maksimum boyut';
$lang['antivirus_maximum_file_size_invalid'] = 'Maksimum dosya boyutu geçersiz.';
$lang['antivirus_maximum_files'] = 'Zip dosyalarýndaki maksimum dosya sayýsý';
$lang['antivirus_maximum_files_invalid'] = 'Maksimum dosya deðeri geçersiz.';
$lang['antivirus_maximum_recursion'] = 'Zip dosyalarýndaki maksimum sýkýþtýrma deðeri';
$lang['antivirus_maximum_recursion_invalid'] = 'Maksimum sýkýþtýrma deðeri geçersiz.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'SSL cloaking scan state is invalid.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'SSL URL mismatch scan state is invalid.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Scan URLs state is invalid.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Sahte Ýmza tarama durumu geçersiz.';
$lang['antivirus_twice_a_day'] = 'Günde 2 kere';
$lang['antivirus_update_interval'] = 'Güncelleme Aralýðý';
$lang['antivirus_updates_per_day_invalid'] = 'Günlük güncelleme deðeri geçersiz.';
