<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'Приложение "Антивирус" использует центральный антивирусный механизм, чтобы отсканировать сеть, FTP, почту и т.д. Это защищает устройства, соединенные с вашей сетью, останавливая вредоносное программное обеспечение, прежде чем оно достигнет ваших пользователей.';
$lang['antivirus_app_name'] = 'Антивирус';
$lang['antivirus_app_tooltip'] = 'Зашифрованные файлы часто используются, чтобы поставить вредоносное программное обеспечение, пожалуйста будьте осторожны, не позволяйте этим типам файлов проникнуть через антивирусный механизм.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Block encrypted archive value is invalid.';
$lang['antivirus_block_encrypted_files'] = 'Блок зашифрованных файлов';
$lang['antivirus_every_two_hours'] = 'Каждые два часа';
$lang['antivirus_maximum_file_size'] = 'Максимальный размер файла Zip';
$lang['antivirus_maximum_file_size_invalid'] = 'Maximum file size is invalid.';
$lang['antivirus_maximum_files'] = 'Максимальное количество файлов Zip';
$lang['antivirus_maximum_files_invalid'] = 'Maximum number of files is invalid.';
$lang['antivirus_maximum_recursion'] = 'Максимальная рекурсия в файлах Zip';
$lang['antivirus_maximum_recursion_invalid'] = 'Maximum recursion is invalid.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'SSL cloaking scan state is invalid.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'SSL URL mismatch scan state is invalid.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Сканирование URL-адреса состоянии недействительна.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Phishing signatures scan state is invalid.';
$lang['antivirus_twice_a_day'] = 'Два раза в день';
$lang['antivirus_update_interval'] = 'Интервал обновления';
$lang['antivirus_updates_per_day_invalid'] = 'Количество обновлений в день является недействительным.';
