#!/bin/sh

# Add sudo entry
#---------------

/usr/sbin/addsudo /usr/bin/freshclam app-antivirus-core

# Deploy default configuration files
#-----------------------------------

logger -p local6.notice -t installer "app-antivirus-core - installing default clamd configuration"
cp /usr/clearos/apps/antivirus/deploy/clamd.conf /etc/clamd.conf

logger -p local6.notice -t installer "app-antivirus-core - installing default freshclam configuration"
cp /usr/clearos/apps/antivirus/deploy/freshclam.conf /etc/freshclam.conf

# Set boot policy
#----------------

logger -p local6.notice -t installer "app-antivirus-core - enabling antivirus server"

if [ -x /etc/rc.d/init.d/clamd ]; then
    /sbin/chkconfig --add clamd >/dev/null 2>&1
fi

/sbin/chkconfig clamd on >/dev/null 2>&1
/sbin/service clamd start >/dev/null 2>&1
