#!/bin/sh

# There seems to be some upgrade ordering sometimes.
# This may no longer be necessary.
#---------------------------------------------------

/usr/bin/clamscan /etc/hosts >/dev/null 2>&1

if [ $? != 0 ]; then
    logger -p local6.notice -t installer "app-antivirus-core - resetting antivirus definitions"
    rm -rf /var/lib/clamav/daily.inc
    rm -rf /var/lib/clamav/main.inc
    /usr/bin/freshclam
fi

# Trigger check for upstream proxy configuration
#-----------------------------------------------

/var/clearos/events/upstream_proxy/antivirus
