<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Gateway Antivirus';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Blok arsip terenkripsi nilainya tidak benar.';
$lang['antivirus_block_encrypted_files'] = 'Blok File Terenskripsi';
$lang['antivirus_every_two_hours'] = 'Setiap Dua Jam';
$lang['antivirus_maximum_file_size'] = 'Ukuran file maksimal dalam format Zip';
$lang['antivirus_maximum_file_size_invalid'] = 'Ukuran file maksimal tidak benar.';
$lang['antivirus_maximum_files'] = 'File Maksimal dalam format Zip';
$lang['antivirus_maximum_files_invalid'] = 'Jumlah maksimal file tidak benar.';
$lang['antivirus_maximum_recursion'] = 'Maksimal Rekursi dalam format Zip';
$lang['antivirus_maximum_recursion_invalid'] = 'Rekursi maksimal tidak benar.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'SSL cloaking scan state is invalid.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'SSL URL mismatch scan state is invalid.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Scan URLs state is invalid.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Phising signatures dipindai dalam keadaan tidak benar.';
$lang['antivirus_twice_a_day'] = 'Dua kali dalam sehari';
$lang['antivirus_update_interval'] = 'Interval pembaruan';
$lang['antivirus_updates_per_day_invalid'] = 'Jumlah update per hari tidak benar.';
