<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Gateway Antivirus';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Blockiere verschlüsselte Archive, dessen Grüße ungültig ist.';
$lang['antivirus_block_encrypted_files'] = 'Verschlüsselte Dateien blockieren';
$lang['antivirus_every_two_hours'] = 'Alle zwei Stunden';
$lang['antivirus_maximum_file_size'] = 'Maximale Dateigröße für Zip Dateien';
$lang['antivirus_maximum_file_size_invalid'] = 'Maximale Dateigröße ist ungültig.';
$lang['antivirus_maximum_files'] = 'Maximale Anzahl von Dateien in Zip Datein';
$lang['antivirus_maximum_files_invalid'] = 'Maximale Anzahl der Dateien ist ungültig.';
$lang['antivirus_maximum_recursion'] = 'Maximale Verschachtelung bei Zip Dateien';
$lang['antivirus_maximum_recursion_invalid'] = 'Maximale Verschachtelung ist ungültig.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'SSL Cloaking Scanstatus ist ungültig.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'SSL URL Mismatch Scanstatus ist ungültig.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Überprüfte URLs sind ungültig.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Phishing Überprüfung ist ungültig.';
$lang['antivirus_twice_a_day'] = 'Zweimal pro Tag';
$lang['antivirus_update_interval'] = 'Update Intervall';
$lang['antivirus_updates_per_day_invalid'] = 'Anzahl der Updates pro Tag ist ungültig.';
