<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Gateway Anti-vírus';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Valor do Bloco encriptado do arquivo é inválido.';
$lang['antivirus_block_encrypted_files'] = 'Bloquear arquivos encriptados';
$lang['antivirus_every_two_hours'] = 'A cada duas horas';
$lang['antivirus_maximum_file_size'] = 'Arquivo de tamanho máximo no arquivo ZIP';
$lang['antivirus_maximum_file_size_invalid'] = 'Tamanho máximo inválido.';
$lang['antivirus_maximum_files'] = 'Número máximo de arquivos no arquivo ZIP';
$lang['antivirus_maximum_files_invalid'] = 'Número máximo de arquivos inválido.';
$lang['antivirus_maximum_recursion'] = 'Número máximo de recursão no arquivo ZIP';
$lang['antivirus_maximum_recursion_invalid'] = 'Recursão máxima inválida.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'Estado de varredura do SSL camuflado é inválido.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'Estado de Varredura de URL SSL é inválido.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Estado da Varredura de URLs é inválido.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Estado de Varredura de assinaturas de Pishing é inválido.';
$lang['antivirus_twice_a_day'] = 'Duas vezes por dia';
$lang['antivirus_update_interval'] = 'Intervalo de Atualicação';
$lang['antivirus_updates_per_day_invalid'] = 'Números de atualizações por dia é inválido.';
