<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = '网关反病毒';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = '阻拦加密存档无效';
$lang['antivirus_block_encrypted_files'] = '阻拦加密文件';
$lang['antivirus_every_two_hours'] = '每两小时';
$lang['antivirus_maximum_file_size'] = '最大Zip文件';
$lang['antivirus_maximum_file_size_invalid'] = '文件最大个头无效。';
$lang['antivirus_maximum_files'] = 'Zip文件中最大文件数';
$lang['antivirus_maximum_files_invalid'] = '文件最大数无效。';
$lang['antivirus_maximum_recursion'] = 'Zip文件最大递归';
$lang['antivirus_maximum_recursion_invalid'] = '最大递归无效';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'SSL cloaking scan state is invalid.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'SSL URL mismatch scan state is invalid.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Scan URLs state is invalid.';
$lang['antivirus_phishing_signatures_state_invalid'] = '网络钓鱼扫描状态无效。';
$lang['antivirus_twice_a_day'] = '每天两次';
$lang['antivirus_update_interval'] = '更新间隔';
$lang['antivirus_updates_per_day_invalid'] = '每天升级次数无效。';
