<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Gateway Antivirus';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Värdet för att blockera krypterade arkiv är ogiltigt.';
$lang['antivirus_block_encrypted_files'] = 'Blockera krypterade filer';
$lang['antivirus_every_two_hours'] = 'Varannan timme';
$lang['antivirus_maximum_file_size'] = 'Maximal filstorlek i Zippade filer';
$lang['antivirus_maximum_file_size_invalid'] = 'Maximal filstorlek är ogiltigt.';
$lang['antivirus_maximum_files'] = 'Maximala antalet filer i Zippade filer';
$lang['antivirus_maximum_files_invalid'] = 'Maximala antalet filer är ogiltigt.';
$lang['antivirus_maximum_recursion'] = 'Maximal antal nivåer i Zippade filer';
$lang['antivirus_maximum_recursion_invalid'] = 'Maximal antal nivåer är ogiltigt.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'SSL cloaking scan state is invalid.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'SSL URL mismatch scan state is invalid.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Scan URLs state is invalid.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Statusen för skanning av signaturer för närfiske är ogiltig.';
$lang['antivirus_twice_a_day'] = 'Två gånger dagligen';
$lang['antivirus_update_interval'] = 'Uppdateringsintervall';
$lang['antivirus_updates_per_day_invalid'] = 'Antalet uppdateringar per dag är ogiltigt.';
