<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Antivirus gateway';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Ongeldige waarde voor versleuteling archief.';
$lang['antivirus_block_encrypted_files'] = 'Blokkeer versleutelde bestanden.';
$lang['antivirus_every_two_hours'] = 'Elke twee uur';
$lang['antivirus_maximum_file_size'] = 'De maximale bestandsgrootte in een zip-bestanden.';
$lang['antivirus_maximum_file_size_invalid'] = 'Ongeldige maximale bestandsgrootte.';
$lang['antivirus_maximum_files'] = 'Het maximaal aantal bestanden in een Zip-bestanden.';
$lang['antivirus_maximum_files_invalid'] = 'Ongeldig maximaal aantal bestanden.';
$lang['antivirus_maximum_recursion'] = 'De maximale recursie in zip-bestanden.';
$lang['antivirus_maximum_recursion_invalid'] = 'Ongeldige recursie.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'Ongeldige waarde SSL cloaking scan.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'Ongeldige SSL URL combinatie.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Ongeldige URL\'s.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Ongeldige status Phishing ondertekeningen.';
$lang['antivirus_twice_a_day'] = 'Twee keer per dag';
$lang['antivirus_update_interval'] = 'Update interval';
$lang['antivirus_updates_per_day_invalid'] = 'Ongeldig aantal updates per dag.';
