<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'Aplikacja antywirusa bramy sieciowej używa centralnego silnika antywirusowego aby skanować strony www, FTP, pocztę oraz inne.  Ochrania on urządzenia podłączone do Twojej sieci zatrzymując szkodliwe oprogramowanie zanim będzie ono miało kontakt z użytkownikiem.';
$lang['antivirus_app_name'] = 'Antywirus bramy sieciowej';
$lang['antivirus_app_tooltip'] = 'Zaszyfrowane pliki często używane są do dostarczania złośliwego oprogramowania, radzimy być ostrożnym przy zezwalaniu na przepuszczanie takich plików przez system antywirusowy.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Podana wartość blokady zaszyfrowanych archiwów jest nieprawidłowa.';
$lang['antivirus_block_encrypted_files'] = 'Blokowanie zaszyfrowanych plików';
$lang['antivirus_every_two_hours'] = 'Co dwie godziny';
$lang['antivirus_maximum_file_size'] = 'Maksymalny rozmiar pliku w archiwach ZIP';
$lang['antivirus_maximum_file_size_invalid'] = 'Podany maksymalny rozmiar pliku jest nieprawidłowy.';
$lang['antivirus_maximum_files'] = 'Maksymalna liczba plików w archiwach ZIP';
$lang['antivirus_maximum_files_invalid'] = 'Podana maksymalna liczba plików jest nieprawidłowa.';
$lang['antivirus_maximum_recursion'] = 'Maksymalna wartość rekurencji w archiwach ZIP';
$lang['antivirus_maximum_recursion_invalid'] = 'Maksymalna wartość rekurencji jest nieprawidłowa.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'Stan skanowania SSL jest nieprawidłowy.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'Stan skanowania niedopasowań URL\'i SSL jest nieprawidłowy.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Stan skanowania URL\'i jest nieprawidłowy.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Stan skanowania sygnatur phishingowych jest nieprawidłowy.';
$lang['antivirus_twice_a_day'] = 'Dwa razy dziennie';
$lang['antivirus_update_interval'] = 'Interwał aktualizacji';
$lang['antivirus_updates_per_day_invalid'] = 'Podana liczba codziennych aktualizacji jest nieprawidłowa.';
