<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['antivirus_app_description'] = 'The Gateway Antivirus app uses a central antivirus engine to scan web, FTP, mail and more.  It protects devices connected to your network by stopping malware before it has a chance to reach your users.';
$lang['antivirus_app_name'] = 'Antywirus bramy sieciowej';
$lang['antivirus_app_tooltip'] = 'Encrypted files are often used to deliver malware, so please be careful about allowing these types of files through the antivirus engine.';
$lang['antivirus_block_encrypted_archive_flag_invalid'] = 'Podana wartość blokady zaszyfrowanych archiwów jest nieprawidłowa.';
$lang['antivirus_block_encrypted_files'] = 'Blokowanie zaszyfrowanych plików';
$lang['antivirus_every_two_hours'] = 'Co dwie godziny';
$lang['antivirus_maximum_file_size'] = 'Maksymalny rozmiar pliku w archiwach ZIP';
$lang['antivirus_maximum_file_size_invalid'] = 'Podany maksymalny rozmiar pliku jest nieprawidłowy.';
$lang['antivirus_maximum_files'] = 'Maksymalna liczba plików w archiwach ZIP';
$lang['antivirus_maximum_files_invalid'] = 'Podana maksymalna liczba plików jest nieprawidłowa.';
$lang['antivirus_maximum_recursion'] = 'Maksymalna wartość rekurencji w archiwach ZIP';
$lang['antivirus_maximum_recursion_invalid'] = 'Maksymalna wartość rekurencji jest nieprawidłowa.';
$lang['antivirus_phishing_always_block_cloak_invalid'] = 'Stan skanowania SSL jest nieprawidłowy.';
$lang['antivirus_phishing_always_block_ssl_mismatch_invalid'] = 'Stan skanowania niedopasowań URL\'i SSL jest nieprawidłowy.';
$lang['antivirus_phishing_scan_urls_state_invalid'] = 'Stan skanowania URL\'i jest nieprawidłowy.';
$lang['antivirus_phishing_signatures_state_invalid'] = 'Stan skanowania sygnatur phishingowych jest nieprawidłowy.';
$lang['antivirus_twice_a_day'] = 'Dwa razy dziennie';
$lang['antivirus_update_interval'] = 'Interwał aktualizacji';
$lang['antivirus_updates_per_day_invalid'] = 'Podana liczba codziennych aktualizacji jest nieprawidłowa.';
